//
//  SamplePlans.swift
//  Health_Insurance_App
//
//  Created by Aaron Aslan on 4/16/26.
//

import Foundation

// TODO: delete this file once you have a dataset with plans

struct SamplePlans {
    static let plans: [PlanVars] = [
        // TODO: delete id here after id becomes a UUID() that persists to a database
        PlanVars(
            id: "001",
            planName: "Sample Plan",
            coName: "Blue Cross",
            deductible: 3000.00,
            premium: 400.00,
            url: "https://www.bcbs.com/",
            oopMax: 7000.00,
            networkType: .pos,
            riskProfile: .lphr,
            drugCoverage: .standard,
            utilizationFit: .low,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "002",
            planName: "Sample Plan",
            coName: "Highmark",
            deductible: 3200.00,
            premium: 375.00,
            url: "https://highmark.com/",
            oopMax: 7700.00,
            networkType: .pos,
            riskProfile: .lphr,
            drugCoverage: .standard,
            utilizationFit: .veryHigh,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "003",
            planName: "Sample Plan",
            coName: "Aetna",
            deductible: 3500.00,
            premium: 315.00,
            url: "https://www.aetna.com/",
            oopMax: 7200.00,
            networkType: .pos,
            riskProfile: .hplr,
            drugCoverage: .poor,
            utilizationFit: .medium,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "004",
            planName: "Sample Plan",
            coName: "Humana",
            deductible: 3800.00,
            premium: 250.00,
            url: "https://www.humana.com/",
            oopMax: 8000.00,
            networkType: .hmo,
            riskProfile: .hplr,
            drugCoverage: .standard,
            utilizationFit: .high,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "005",
            planName: "Sample Plan",
            coName: "Aetna",
            deductible: 4000.00,
            premium: 215.00,
            url: "https://www.aetna.com/",
            oopMax: 8250.00,
            networkType: .ppo,
            riskProfile: .balanced,
            drugCoverage: .standard,
            utilizationFit: .veryHigh,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "006",
            planName: "Sample Plan",
            coName: "Humana",
            deductible: 3200.00,
            premium: 400.00,
            url: "https://www.humana.com/",
            oopMax: 7000.00,
            networkType: .epo,
            riskProfile: .balanced,
            drugCoverage: .standard,
            utilizationFit: .high,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "007",
            planName: "Sample Plan",
            coName: "Blue Cross",
            deductible: 3800.00,
            premium: 210.00,
            url: "https://www.bcbs.com/",
            oopMax: 7500.00,
            networkType: .indemnity,
            riskProfile: .hplr,
            drugCoverage: .poor,
            utilizationFit: .high,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "008",
            planName: "Sample Plan",
            coName: "Aetna",
            deductible: 4100.00,
            premium: 190.00,
            url: "https://www.aetna.com/",
            oopMax: 8000.00,
            networkType: .hmo,
            riskProfile: .hplr,
            drugCoverage: .strong,
            utilizationFit: .low,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "009",
            planName: "Sample Plan",
            coName: "Cigna",
            deductible: 2500.00,
            premium: 450.00,
            url: "https://www.cigna.com/",
            oopMax: 6500.00,
            networkType: .indemnity,
            riskProfile: .hplr,
            drugCoverage: .standard,
            utilizationFit: .veryHigh,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "010",
            planName: "Sample Plan",
            coName: "UnitedHealthcare",
            deductible: 2800.00,
            premium: 420.00,
            url: "https://www.uhc.com/",
            oopMax: 6800.00,
            networkType: .hmo,
            riskProfile: .hplr,
            drugCoverage: .poor,
            utilizationFit: .high,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "011",
            planName: "Sample Plan",
            coName: "Kaiser Permanente",
            deductible: 1500.00,
            premium: 480.00,
            url: "https://www.kaiserpermanente.org/",
            oopMax: 5500.00,
            networkType: .indemnity,
            riskProfile: .balanced,
            drugCoverage: .strong,
            utilizationFit: .high,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "012",
            planName: "Sample Plan",
            coName: "Anthem",
            deductible: 3100.00,
            premium: 340.00,
            url: "https://www.anthem.com/",
            oopMax: 7100.00,
            networkType: .pos,
            riskProfile: .hplr,
            drugCoverage: .standard,
            utilizationFit: .medium,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "013",
            planName: "Sample Plan",
            coName: "Molina Healthcare",
            deductible: 4500.00,
            premium: 180.00,
            url: "https://www.molinahealthcare.com/",
            oopMax: 8200.00,
            networkType: .hmo,
            riskProfile: .lphr,
            drugCoverage: .strong,
            utilizationFit: .high,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "014",
            planName: "Sample Plan",
            coName: "Oscar Health",
            deductible: 3600.00,
            premium: 300.00,
            url: "https://www.hioscar.com/",
            oopMax: 7400.00,
            networkType: .ppo,
            riskProfile: .balanced,
            drugCoverage: .veryStrong,
            utilizationFit: .veryHigh,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "015",
            planName: "Sample Plan",
            coName: "Centene",
            deductible: 4200.00,
            premium: 200.00,
            url: "https://www.centene.com/",
            oopMax: 8100.00,
            networkType: .pffs,
            riskProfile: .hplr,
            drugCoverage: .veryStrong,
            utilizationFit: .low,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "016",
            planName: "Sample Plan",
            coName: "WellCare",
            deductible: 3900.00,
            premium: 230.00,
            url: "https://www.wellcare.com/",
            oopMax: 7900.00,
            networkType: .pffs,
            riskProfile: .lphr,
            drugCoverage: .strong,
            utilizationFit: .medium,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "017",
            planName: "Sample Plan",
            coName: "Ambetter",
            deductible: 4400.00,
            premium: 175.00,
            url: "https://www.ambetter.com/",
            oopMax: 8300.00,
            networkType: .hmo,
            riskProfile: .lphr,
            drugCoverage: .poor,
            utilizationFit: .veryHigh,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "018",
            planName: "Sample Plan",
            coName: "Blue Cross",
            deductible: 2200.00,
            premium: 500.00,
            url: "https://www.bcbs.com/",
            oopMax: 6200.00,
            networkType: .pos,
            riskProfile: .balanced,
            drugCoverage: .veryStrong,
            utilizationFit: .veryHigh,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "019",
            planName: "Sample Plan",
            coName: "Highmark",
            deductible: 2900.00,
            premium: 395.00,
            url: "https://highmark.com/",
            oopMax: 6900.00,
            networkType: .pffs,
            riskProfile: .balanced,
            drugCoverage: .veryStrong,
            utilizationFit: .low,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "020",
            planName: "Sample Plan",
            coName: "Aetna",
            deductible: 3300.00,
            premium: 330.00,
            url: "https://www.aetna.com/",
            oopMax: 7300.00,
            networkType: .ppo,
            riskProfile: .lphr,
            drugCoverage: .poor,
            utilizationFit: .medium,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "021",
            planName: "Sample Plan",
            coName: "Humana",
            deductible: 3700.00,
            premium: 260.00,
            url: "https://www.humana.com/",
            oopMax: 7800.00,
            networkType: .epo,
            riskProfile: .balanced,
            drugCoverage: .veryStrong,
            utilizationFit: .high,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "022",
            planName: "Sample Plan",
            coName: "Cigna",
            deductible: 4600.00,
            premium: 165.00,
            url: "https://www.cigna.com/",
            oopMax: 8400.00,
            networkType: .pos,
            riskProfile: .balanced,
            drugCoverage: .strong,
            utilizationFit: .veryHigh,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "023",
            planName: "Sample Plan",
            coName: "UnitedHealthcare",
            deductible: 1800.00,
            premium: 460.00,
            url: "https://www.uhc.com/",
            oopMax: 5800.00,
            networkType: .indemnity,
            riskProfile: .balanced,
            drugCoverage: .poor,
            utilizationFit: .medium,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "024",
            planName: "Sample Plan",
            coName: "Kaiser Permanente",
            deductible: 2000.00,
            premium: 440.00,
            url: "https://www.kaiserpermanente.org/",
            oopMax: 6000.00,
            networkType: .epo,
            riskProfile: .balanced,
            drugCoverage: .poor,
            utilizationFit: .medium,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "025",
            planName: "Sample Plan",
            coName: "Anthem",
            deductible: 3400.00,
            premium: 310.00,
            url: "https://www.anthem.com/",
            oopMax: 7350.00,
            networkType: .pffs,
            riskProfile: .balanced,
            drugCoverage: .standard,
            utilizationFit: .veryHigh,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "026",
            planName: "Sample Plan",
            coName: "Molina Healthcare",
            deductible: 4300.00,
            premium: 185.00,
            url: "https://www.molinahealthcare.com/",
            oopMax: 8150.00,
            networkType: .indemnity,
            riskProfile: .lphr,
            drugCoverage: .poor,
            utilizationFit: .high,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "027",
            planName: "Sample Plan",
            coName: "Oscar Health",
            deductible: 3000.00,
            premium: 360.00,
            url: "https://www.hioscar.com/",
            oopMax: 7000.00,
            networkType: .indemnity,
            riskProfile: .hplr,
            drugCoverage: .veryStrong,
            utilizationFit: .veryHigh,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "028",
            planName: "Sample Plan",
            coName: "Centene",
            deductible: 4800.00,
            premium: 155.00,
            url: "https://www.centene.com/",
            oopMax: 8500.00,
            networkType: .pos,
            riskProfile: .balanced,
            drugCoverage: .strong,
            utilizationFit: .low,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "029",
            planName: "Sample Plan",
            coName: "WellCare",
            deductible: 3500.00,
            premium: 275.00,
            url: "https://www.wellcare.com/",
            oopMax: 7450.00,
            networkType: .pos,
            riskProfile: .balanced,
            drugCoverage: .poor,
            utilizationFit: .medium,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "030",
            planName: "Sample Plan",
            coName: "Ambetter",
            deductible: 4700.00,
            premium: 160.00,
            url: "https://www.ambetter.com/",
            oopMax: 8450.00,
            networkType: .epo,
            riskProfile: .balanced,
            drugCoverage: .poor,
            utilizationFit: .low,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "031",
            planName: "Sample Plan",
            coName: "Blue Cross",
            deductible: 2600.00,
            premium: 410.00,
            url: "https://www.bcbs.com/",
            oopMax: 6600.00,
            networkType: .epo,
            riskProfile: .hplr,
            drugCoverage: .poor,
            utilizationFit: .high,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "032",
            planName: "Sample Plan",
            coName: "Highmark",
            deductible: 3050.00,
            premium: 355.00,
            url: "https://highmark.com/",
            oopMax: 7050.00,
            networkType: .pffs,
            riskProfile: .lphr,
            drugCoverage: .veryStrong,
            utilizationFit: .high,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "033",
            planName: "Sample Plan",
            coName: "Aetna",
            deductible: 3900.00,
            premium: 235.00,
            url: "https://www.aetna.com/",
            oopMax: 7850.00,
            networkType: .indemnity,
            riskProfile: .hplr,
            drugCoverage: .strong,
            utilizationFit: .low,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "034",
            planName: "Sample Plan",
            coName: "Humana",
            deductible: 2400.00,
            premium: 430.00,
            url: "https://www.humana.com/",
            oopMax: 6400.00,
            networkType: .epo,
            riskProfile: .lphr,
            drugCoverage: .veryStrong,
            utilizationFit: .veryHigh,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "035",
            planName: "Sample Plan",
            coName: "Cigna",
            deductible: 3200.00,
            premium: 345.00,
            url: "https://www.cigna.com/",
            oopMax: 7150.00,
            networkType: .hmo,
            riskProfile: .lphr,
            drugCoverage: .strong,
            utilizationFit: .low,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "036",
            planName: "Sample Plan",
            coName: "UnitedHealthcare",
            deductible: 4900.00,
            premium: 150.00,
            url: "https://www.uhc.com/",
            oopMax: 8550.00,
            networkType: .epo,
            riskProfile: .lphr,
            drugCoverage: .strong,
            utilizationFit: .high,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "037",
            planName: "Sample Plan",
            coName: "Kaiser Permanente",
            deductible: 1700.00,
            premium: 470.00,
            url: "https://www.kaiserpermanente.org/",
            oopMax: 5700.00,
            networkType: .epo,
            riskProfile: .hplr,
            drugCoverage: .standard,
            utilizationFit: .medium,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "038",
            planName: "Sample Plan",
            coName: "Anthem",
            deductible: 3650.00,
            premium: 285.00,
            url: "https://www.anthem.com/",
            oopMax: 7550.00,
            networkType: .ppo,
            riskProfile: .hplr,
            drugCoverage: .poor,
            utilizationFit: .medium,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "039",
            planName: "Sample Plan",
            coName: "Molina Healthcare",
            deductible: 4150.00,
            premium: 195.00,
            url: "https://www.molinahealthcare.com/",
            oopMax: 8050.00,
            networkType: .indemnity,
            riskProfile: .hplr,
            drugCoverage: .standard,
            utilizationFit: .low,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "040",
            planName: "Sample Plan",
            coName: "Oscar Health",
            deductible: 2750.00,
            premium: 385.00,
            url: "https://www.hioscar.com/",
            oopMax: 6750.00,
            networkType: .pffs,
            riskProfile: .hplr,
            drugCoverage: .poor,
            utilizationFit: .high,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "041",
            planName: "Sample Plan",
            coName: "Centene",
            deductible: 3450.00,
            premium: 305.00,
            url: "https://www.centene.com/",
            oopMax: 7250.00,
            networkType: .ppo,
            riskProfile: .lphr,
            drugCoverage: .strong,
            utilizationFit: .low,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "042",
            planName: "Sample Plan",
            coName: "WellCare",
            deductible: 5000.00,
            premium: 145.00,
            url: "https://www.wellcare.com/",
            oopMax: 8600.00,
            networkType: .pffs,
            riskProfile: .balanced,
            drugCoverage: .veryStrong,
            utilizationFit: .medium,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "043",
            planName: "Sample Plan",
            coName: "Ambetter",
            deductible: 3750.00,
            premium: 245.00,
            url: "https://www.ambetter.com/",
            oopMax: 7700.00,
            networkType: .ppo,
            riskProfile: .lphr,
            drugCoverage: .standard,
            utilizationFit: .low,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "044",
            planName: "Sample Plan",
            coName: "Blue Cross",
            deductible: 1900.00,
            premium: 490.00,
            url: "https://www.bcbs.com/",
            oopMax: 5900.00,
            networkType: .ppo,
            riskProfile: .lphr,
            drugCoverage: .strong,
            utilizationFit: .medium,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "045",
            planName: "Sample Plan",
            coName: "Highmark",
            deductible: 3550.00,
            premium: 290.00,
            url: "https://highmark.com/",
            oopMax: 7550.00,
            networkType: .hmo,
            riskProfile: .balanced,
            drugCoverage: .veryStrong,
            utilizationFit: .veryHigh,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "046",
            planName: "Sample Plan",
            coName: "Aetna",
            deductible: 4250.00,
            premium: 205.00,
            url: "https://www.aetna.com/",
            oopMax: 8200.00,
            networkType: .hmo,
            riskProfile: .lphr,
            drugCoverage: .veryStrong,
            utilizationFit: .high,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "047",
            planName: "Sample Plan",
            coName: "Humana",
            deductible: 2100.00,
            premium: 445.00,
            url: "https://www.humana.com/",
            oopMax: 6100.00,
            networkType: .hmo,
            riskProfile: .hplr,
            drugCoverage: .standard,
            utilizationFit: .low,
            coverageScope: .regional,
        ),
        
        PlanVars(
            id: "048",
            planName: "Sample Plan",
            coName: "Cigna",
            deductible: 3350.00,
            premium: 320.00,
            url: "https://www.cigna.com/",
            oopMax: 7250.00,
            networkType: .ppo,
            riskProfile: .balanced,
            drugCoverage: .veryStrong,
            utilizationFit: .medium,
            coverageScope: .national,
        ),
        
        PlanVars(
            id: "049",
            planName: "Sample Plan",
            coName: "UnitedHealthcare",
            deductible: 2300.00,
            premium: 425.00,
            url: "https://www.uhc.com/",
            oopMax: 6300.00,
            networkType: .ppo,
            riskProfile: .hplr,
            drugCoverage: .strong,
            utilizationFit: .veryHigh,
            coverageScope: .local,
        ),
        
        PlanVars(
            id: "050",
            planName: "Sample Plan",
            coName: "Kaiser Permanente",
            deductible: 4050.00,
            premium: 220.00,
            url: "https://www.kaiserpermanente.org/",
            oopMax: 7950.00,
            networkType: .pffs,
            riskProfile: .lphr,
            drugCoverage: .standard,
            utilizationFit: .medium,
            coverageScope: .local,
        )
    ]
}
